USE [master]
GO

/****** Object:  Database [ARTSHOP]    Script Date: 14/03/2021 17:11:37 ******/
CREATE DATABASE [ARTSHOP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ARTSHOP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ARTSHOP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ARTSHOP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ARTSHOP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ARTSHOP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ARTSHOP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ARTSHOP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ARTSHOP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ARTSHOP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ARTSHOP] SET ARITHABORT OFF 
GO

ALTER DATABASE [ARTSHOP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ARTSHOP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ARTSHOP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ARTSHOP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ARTSHOP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ARTSHOP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ARTSHOP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ARTSHOP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ARTSHOP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ARTSHOP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ARTSHOP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ARTSHOP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ARTSHOP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ARTSHOP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ARTSHOP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ARTSHOP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ARTSHOP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ARTSHOP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ARTSHOP] SET  MULTI_USER 
GO

ALTER DATABASE [ARTSHOP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ARTSHOP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ARTSHOP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ARTSHOP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ARTSHOP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ARTSHOP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ARTSHOP] SET  READ_WRITE 
GO

