// <auto-generated />
using System;
using E_Shop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210423010407_pdetailsFormatId")]
    partial class pdetailsFormatId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "French_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Shop.Entities.Avi", b =>
                {
                    b.Property<int>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<DateTime?>("ADate")
                        .HasColumnType("datetime")
                        .HasColumnName("A_DATE");

                    b.Property<short?>("ANote")
                        .HasColumnType("smallint")
                        .HasColumnName("A_NOTE");

                    b.Property<DateTime?>("ARepdate")
                        .HasColumnType("datetime")
                        .HasColumnName("A_REPDATE");

                    b.Property<string>("AReponse")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("A_REPONSE");

                    b.Property<string>("ATexte")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("A_TEXTE");

                    b.HasKey("Prodid", "Id", "Btqid");

                    b.HasIndex(new[] { "Id" }, "AVIS2_FK");

                    b.HasIndex(new[] { "Btqid" }, "AVIS3_FK");

                    b.HasIndex(new[] { "Prodid" }, "AVIS_FK");

                    b.ToTable("AVIS");
                });

            modelBuilder.Entity("E_Shop.Entities.BcDetail", b =>
                {
                    b.Property<int>("Btqcmdid")
                        .HasColumnType("int")
                        .HasColumnName("BTQCMDID");

                    b.Property<int>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.Property<int>("Livraisonid")
                        .HasColumnType("int")
                        .HasColumnName("LIVRAISONID");

                    b.Property<short?>("BCmdQteprod")
                        .HasColumnType("smallint")
                        .HasColumnName("B_CMD_QTEPROD");

                    b.HasKey("Btqcmdid", "Prodid", "Livraisonid");

                    b.HasIndex(new[] { "Prodid" }, "COMPORTER2_FK");

                    b.HasIndex(new[] { "Livraisonid" }, "COMPORTER3_FK");

                    b.HasIndex(new[] { "Btqcmdid" }, "COMPORTER_FK");

                    b.ToTable("BC_DETAIL");
                });

            modelBuilder.Entity("E_Shop.Entities.Boutique", b =>
                {
                    b.Property<int>("Btqid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BTQID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BDescriptionC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("B_DESCRIPTION_C");

                    b.Property<string>("BDescriptionL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("B_DESCRIPTION_L");

                    b.Property<string>("Bic")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("BIC");

                    b.Property<string>("BtqNom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BTQNOM");

                    b.Property<string>("Btqmessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BTQMESSAGE");

                    b.Property<string>("Btqseo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BTQSEO");

                    b.Property<string>("Btqtel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BTQTEL");

                    b.Property<string>("Btqtmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BTQTMAIL");

                    b.Property<int?>("Ca")
                        .HasColumnType("int")
                        .HasColumnName("CA");

                    b.Property<string>("Clerib")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CLERIB");

                    b.Property<string>("Codebanque")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CODEBANQUE");

                    b.Property<string>("Codeguichet")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CODEGUICHET");

                    b.Property<string>("Codenaf")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("CODENAF");

                    b.Property<string>("DateCreation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DATECREATION");

                    b.Property<string>("Domiciliation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOMICILIATION");

                    b.Property<string>("Iban")
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)")
                        .HasColumnName("IBAN");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("Nbsalarie")
                        .HasColumnType("int")
                        .HasColumnName("NBSALARIE");

                    b.Property<string>("Numcompte")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("NUMCOMPTE");

                    b.Property<int>("Politiqueid")
                        .HasColumnType("int")
                        .HasColumnName("POLITIQUEID");

                    b.Property<string>("Raisonsociale")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RAISONSOCIALE");

                    b.Property<string>("Siren")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("SIREN");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("SIRET");

                    b.Property<string>("Siteweb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SITEWEB");

                    b.Property<string>("Statutjuridique")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("STATUTJURIDIQUE");

                    b.Property<string>("Titulaire")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)")
                        .HasColumnName("TITULAIRE");

                    b.HasKey("Btqid");

                    b.HasIndex(new[] { "Politiqueid" }, "APPLIQUER_FK");

                    b.HasIndex(new[] { "Id" }, "CREER_FK");

                    b.ToTable("BOUTIQUE");
                });

            modelBuilder.Entity("E_Shop.Entities.Boutiquecommande", b =>
                {
                    b.Property<int>("Btqcmdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BTQCMDID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Btqcmddatecrea")
                        .HasColumnType("datetime")
                        .HasColumnName("BTQCMDDATECREA");

                    b.Property<DateTime?>("Btqcmddatedebut")
                        .HasColumnType("datetime")
                        .HasColumnName("BTQCMDDATEDEBUT");

                    b.Property<DateTime?>("Btqcmddatefin")
                        .HasColumnType("datetime")
                        .HasColumnName("BTQCMDDATEFIN");

                    b.Property<int>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<int?>("Cltcmdid")
                        .HasColumnType("int")
                        .HasColumnName("CLTCMDID");

                    b.Property<int>("Cmdetatid")
                        .HasColumnType("int")
                        .HasColumnName("CMDETATID");

                    b.Property<int?>("Litigeid")
                        .HasColumnType("int")
                        .HasColumnName("LITIGEID");

                    b.HasKey("Btqcmdid");

                    b.HasIndex(new[] { "Cltcmdid" }, "ASSOCIER_FK");

                    b.HasIndex(new[] { "Cmdetatid" }, "COMPRENDRE_FK");

                    b.HasIndex(new[] { "Litigeid" }, "ENGENDRER2_FK");

                    b.HasIndex(new[] { "Btqid" }, "RECEVOIR_FK");

                    b.ToTable("BOUTIQUECOMMANDE");
                });

            modelBuilder.Entity("E_Shop.Entities.Categorie", b =>
                {
                    b.Property<int>("Categorieid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIEID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categorienom")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CATEGORIENOM");

                    b.HasKey("Categorieid");

                    b.ToTable("CATEGORIE");
                });

            modelBuilder.Entity("E_Shop.Entities.Catnav", b =>
                {
                    b.Property<int>("Categorieid")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIEID");

                    b.Property<int>("CatCategorieid")
                        .HasColumnType("int")
                        .HasColumnName("CAT_CATEGORIEID");

                    b.HasKey("Categorieid", "CatCategorieid");

                    b.HasIndex(new[] { "CatCategorieid" }, "REGROUPER2_FK");

                    b.HasIndex(new[] { "Categorieid" }, "REGROUPER_FK");

                    b.ToTable("CATNAV");
                });

            modelBuilder.Entity("E_Shop.Entities.CcDetail", b =>
                {
                    b.Property<int>("Cltcmdid")
                        .HasColumnType("int")
                        .HasColumnName("CLTCMDID");

                    b.Property<int>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.Property<int>("Livraisonid")
                        .HasColumnType("int")
                        .HasColumnName("LIVRAISONID");

                    b.Property<short?>("CCmdQteprod")
                        .HasColumnType("smallint")
                        .HasColumnName("C_CMD_QTEPROD");

                    b.HasKey("Cltcmdid", "Prodid", "Livraisonid");

                    b.HasIndex(new[] { "Prodid" }, "LISTER2_FK");

                    b.HasIndex(new[] { "Livraisonid" }, "LISTER3_FK");

                    b.HasIndex(new[] { "Cltcmdid" }, "LISTER_FK");

                    b.ToTable("CC_DETAIL");
                });

            modelBuilder.Entity("E_Shop.Entities.Civilite", b =>
                {
                    b.Property<int>("Civid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CIVID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrege")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ABREGE");

                    b.Property<string>("Complet")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("COMPLET");

                    b.HasKey("Civid");

                    b.ToTable("CIVILITE");
                });

            modelBuilder.Entity("E_Shop.Entities.Clientcommande", b =>
                {
                    b.Property<int>("Cltcmdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLTCMDID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Cltcmddate")
                        .HasColumnType("datetime")
                        .HasColumnName("CLTCMDDATE");

                    b.Property<DateTime?>("Cltcmddatedebut")
                        .HasColumnType("datetime")
                        .HasColumnName("CLTCMDDATEDEBUT");

                    b.Property<DateTime?>("Cltcmddatefin")
                        .HasColumnType("datetime")
                        .HasColumnName("CLTCMDDATEFIN");

                    b.Property<int>("Cmdetatid")
                        .HasColumnType("int")
                        .HasColumnName("CMDETATID");

                    b.Property<int?>("Factureid")
                        .HasColumnType("int")
                        .HasColumnName("FACTUREID");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("Paiementid")
                        .HasColumnType("int")
                        .HasColumnName("PAIEMENTID");

                    b.HasKey("Cltcmdid");

                    b.HasIndex(new[] { "Cmdetatid" }, "DETENIR_FK");

                    b.HasIndex(new[] { "Factureid" }, "GENERER2_FK");

                    b.HasIndex(new[] { "Id" }, "PASSER_FK");

                    b.HasIndex(new[] { "Paiementid" }, "PRENDRE2_FK");

                    b.ToTable("CLIENTCOMMANDE");
                });

            modelBuilder.Entity("E_Shop.Entities.Cmdetat", b =>
                {
                    b.Property<int>("Cmdetatid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CMDETATID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cmdetat1")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CMDETAT");

                    b.HasKey("Cmdetatid");

                    b.ToTable("CMDETAT");
                });

            modelBuilder.Entity("E_Shop.Entities.Echange", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.Property<int>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<string>("EQuest")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("E_QUEST");

                    b.Property<DateTime?>("EQuestdate")
                        .HasColumnType("datetime")
                        .HasColumnName("E_QUESTDATE");

                    b.Property<string>("ERep")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("E_REP");

                    b.Property<DateTime?>("ERepdate")
                        .HasColumnType("datetime")
                        .HasColumnName("E_REPDATE");

                    b.HasKey("Id", "Prodid", "Btqid");

                    b.HasIndex(new[] { "Prodid" }, "ECHANGE2_FK");

                    b.HasIndex(new[] { "Btqid" }, "ECHANGE3_FK");

                    b.HasIndex(new[] { "Id" }, "ECHANGE_FK");

                    b.ToTable("ECHANGE");
                });

            modelBuilder.Entity("E_Shop.Entities.Facture", b =>
                {
                    b.Property<int>("Factureid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FACTUREID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cltcmdid")
                        .HasColumnType("int")
                        .HasColumnName("CLTCMDID");

                    b.Property<string>("Factlien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FACTLIEN");

                    b.HasKey("Factureid");

                    b.HasIndex(new[] { "Cltcmdid" }, "GENERER_FK");

                    b.ToTable("FACTURE");
                });

            modelBuilder.Entity("E_Shop.Entities.Format", b =>
                {
                    b.Property<int>("Formatid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FORMATID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Litre")
                        .HasColumnType("decimal(9,3)")
                        .HasColumnName("LITRE");

                    b.Property<decimal?>("Poids")
                        .HasColumnType("decimal(9,3)")
                        .HasColumnName("POIDS");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PRIX");

                    b.Property<int>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.HasKey("Formatid");

                    b.HasIndex(new[] { "Prodid" }, "PESER_FK");

                    b.ToTable("FORMAT");
                });

            modelBuilder.Entity("E_Shop.Entities.Identification", b =>
                {
                    b.Property<int>("Identid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDENTID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Civid")
                        .HasColumnType("int")
                        .HasColumnName("CIVID");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Nom")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("NOM");

                    b.Property<string>("Prenom")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("PRENOM");

                    b.Property<string>("Tel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TEL");

                    b.HasKey("Identid");

                    b.HasIndex(new[] { "Civid" }, "ETRE_FK");

                    b.HasIndex(new[] { "Id" }, "IDENTIFIER_FK");

                    b.ToTable("IDENTIFICATION");
                });

            modelBuilder.Entity("E_Shop.Entities.Litige", b =>
                {
                    b.Property<int>("Litigeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LITIGEID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Btqcmdid")
                        .HasColumnType("int")
                        .HasColumnName("BTQCMDID");

                    b.Property<string>("Ltgmsg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LTGMSG");

                    b.Property<int?>("Remboursementid")
                        .HasColumnType("int")
                        .HasColumnName("REMBOURSEMENTID");

                    b.Property<int?>("Rempid")
                        .HasColumnType("int")
                        .HasColumnName("REMPID");

                    b.HasKey("Litigeid");

                    b.HasIndex(new[] { "Remboursementid" }, "DONNER2_FK");

                    b.HasIndex(new[] { "Btqcmdid" }, "ENGENDRER_FK");

                    b.HasIndex(new[] { "Rempid" }, "ENVOYER2_FK");

                    b.ToTable("LITIGE");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraison", b =>
                {
                    b.Property<int>("Livraisonid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LIVRAISONID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Dateenvoi")
                        .HasColumnType("datetime")
                        .HasColumnName("DATEENVOI");

                    b.Property<int>("Localisationid")
                        .HasColumnType("int")
                        .HasColumnName("LOCALISATIONID");

                    b.Property<int>("Lvretatid")
                        .HasColumnType("int")
                        .HasColumnName("LVRETATID");

                    b.Property<int>("Lvrtypid")
                        .HasColumnType("int")
                        .HasColumnName("LVRTYPID");

                    b.Property<string>("Suivilien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUIVILIEN");

                    b.Property<string>("Suivinum")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUIVINUM");

                    b.HasKey("Livraisonid");

                    b.HasIndex(new[] { "Lvretatid" }, "CARACTERISER_FK");

                    b.HasIndex(new[] { "Lvrtypid" }, "DEFINIR_FK");

                    b.HasIndex(new[] { "Localisationid" }, "DESTINER_FK");

                    b.ToTable("LIVRAISON");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraisonetat", b =>
                {
                    b.Property<int>("Lvretatid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LVRETATID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lvretat")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("LVRETAT");

                    b.HasKey("Lvretatid");

                    b.ToTable("LIVRAISONETAT");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraisontype", b =>
                {
                    b.Property<int>("Lvrtypid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LVRTYPID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<decimal?>("Lvrcout")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("LVRCOUT");

                    b.Property<decimal?>("LvrcoutPsup")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("LVRCOUTPSUP");

                    b.Property<short?>("Lvrdelai")
                        .HasColumnType("smallint")
                        .HasColumnName("LVRDELAI");

                    b.Property<string>("Lvrdesignation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LVRDESIGNATION");

                    b.HasKey("Lvrtypid");

                    b.HasIndex("Btqid");

                    b.ToTable("LIVRAISONTYPE");
                });

            modelBuilder.Entity("E_Shop.Entities.Localisation", b =>
                {
                    b.Property<int>("Localisationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOCALISATIONID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADRESSE");

                    b.Property<int?>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<string>("Codepostal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CODEPOSTAL");

                    b.Property<string>("Departement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DEPARTEMENT");

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Num")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NUM");

                    b.Property<string>("Pays")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PAYS");

                    b.Property<string>("PrNom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PR_NOM");

                    b.Property<string>("Rue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RUE");

                    b.Property<string>("Ville")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("VILLE");

                    b.HasKey("Localisationid");

                    b.HasIndex(new[] { "Id" }, "POSSEDER_FK");

                    b.HasIndex(new[] { "Btqid" }, "SITUER_FK");

                    b.ToTable("LOCALISATION");
                });

            modelBuilder.Entity("E_Shop.Entities.Medium", b =>
                {
                    b.Property<int>("Mediaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MEDIAID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<int?>("Categorieid")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIEID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FILENAME");

                    b.Property<bool?>("Image")
                        .HasColumnType("bit")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Lien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LIEN");

                    b.Property<int?>("Litigeid")
                        .HasColumnType("int")
                        .HasColumnName("LITIGEID");

                    b.Property<int?>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.Property<bool?>("Video")
                        .HasColumnType("bit")
                        .HasColumnName("VIDEO");

                    b.HasKey("Mediaid");

                    b.HasIndex(new[] { "Btqid" }, "BOUTMEDIA_FK");

                    b.HasIndex(new[] { "Categorieid" }, "CATMEDIA_FK");

                    b.HasIndex(new[] { "Litigeid" }, "LTGMEDIA_FK");

                    b.HasIndex(new[] { "Prodid" }, "PRODMEDIA_FK");

                    b.ToTable("MEDIA");
                });

            modelBuilder.Entity("E_Shop.Entities.Moyendepaiement", b =>
                {
                    b.Property<int>("Mdpid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MDPID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CbNum")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("CB_NUM");

                    b.Property<string>("CbTitulaire")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)")
                        .HasColumnName("CB_TITULAIRE");

                    b.Property<string>("CbType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CB_TYPE");

                    b.Property<string>("Cvc")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("CVC");

                    b.Property<DateTime?>("Dateexp")
                        .HasColumnType("datetime")
                        .HasColumnName("DATEEXP");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.HasKey("Mdpid");

                    b.HasIndex(new[] { "Id" }, "UTILISER_FK");

                    b.ToTable("MOYENDEPAIEMENT");
                });

            modelBuilder.Entity("E_Shop.Entities.PDetail", b =>
                {
                    b.Property<int>("Panierid")
                        .HasColumnType("int")
                        .HasColumnName("PANIERID");

                    b.Property<int>("Prodid")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.Property<int>("Formatid")
                        .HasColumnType("int")
                        .HasColumnName("FORMATID");

                    b.Property<short?>("PQteprod")
                        .HasColumnType("smallint")
                        .HasColumnName("P_QTEPROD");

                    b.HasKey("Panierid", "Prodid", "Formatid");

                    b.HasIndex("Formatid");

                    b.HasIndex(new[] { "Prodid" }, "CONTENIR2_FK");

                    b.HasIndex(new[] { "Panierid" }, "CONTENIR_FK");

                    b.ToTable("P_DETAIL");
                });

            modelBuilder.Entity("E_Shop.Entities.PaieTransact", b =>
                {
                    b.Property<int>("Paiementid")
                        .HasColumnType("int")
                        .HasColumnName("PAIEMENTID");

                    b.Property<int>("Transactionid")
                        .HasColumnType("int")
                        .HasColumnName("TRANSACTIONID");

                    b.HasKey("Paiementid", "Transactionid");

                    b.HasIndex(new[] { "Transactionid" }, "TRACER2_FK");

                    b.HasIndex(new[] { "Paiementid" }, "TRACER_FK");

                    b.ToTable("PAIE_TRANSACT");
                });

            modelBuilder.Entity("E_Shop.Entities.Paiement", b =>
                {
                    b.Property<int>("Paiementid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAIEMENTID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cltcmdid")
                        .HasColumnType("int")
                        .HasColumnName("CLTCMDID");

                    b.Property<int>("Mdpid")
                        .HasColumnType("int")
                        .HasColumnName("MDPID");

                    b.Property<decimal?>("PMontant")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("P_MONTANT");

                    b.HasKey("Paiementid");

                    b.HasIndex(new[] { "Cltcmdid" }, "PRENDRE_FK");

                    b.HasIndex(new[] { "Mdpid" }, "REGLER_FK");

                    b.ToTable("PAIEMENT");
                });

            modelBuilder.Entity("E_Shop.Entities.Panier", b =>
                {
                    b.Property<int>("Panierid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PANIERID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.HasKey("Panierid");

                    b.HasIndex(new[] { "Id" }, "DISPOSER_FK");

                    b.ToTable("PANIER");
                });

            modelBuilder.Entity("E_Shop.Entities.Partenaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Panierid")
                        .HasColumnType("int")
                        .HasColumnName("PANIERID");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Panierid" }, "DISPOSER2_FK");

                    b.ToTable("PARTENAIRE");
                });

            modelBuilder.Entity("E_Shop.Entities.Politique", b =>
                {
                    b.Property<int>("Politiqueid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POLITIQUEID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Echange")
                        .HasColumnType("bit")
                        .HasColumnName("ECHANGE");

                    b.Property<string>("Pltqdescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PLTQDESCRIPTION");

                    b.Property<bool?>("Remboursement")
                        .HasColumnType("bit")
                        .HasColumnName("REMBOURSEMENT");

                    b.HasKey("Politiqueid");

                    b.ToTable("POLITIQUE");
                });

            modelBuilder.Entity("E_Shop.Entities.ProdLvrType", b =>
                {
                    b.Property<int>("LvrTypeId")
                        .HasColumnType("int")
                        .HasColumnName("LVRTYPEID");

                    b.Property<int>("ProdId")
                        .HasColumnType("int")
                        .HasColumnName("PRODID");

                    b.HasKey("LvrTypeId", "ProdId");

                    b.HasIndex(new[] { "LvrTypeId" }, "LVRTYPE_FK");

                    b.HasIndex(new[] { "ProdId" }, "PROD_FK");

                    b.ToTable("PRODLVRTYPE");
                });

            modelBuilder.Entity("E_Shop.Entities.Produit", b =>
                {
                    b.Property<int>("Prodid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRODID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<int>("Categorieid")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORIEID");

                    b.Property<short?>("Disponibilite")
                        .HasColumnType("smallint")
                        .HasColumnName("DISPONIBILITE");

                    b.Property<string>("PDescriptionC")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("P_DESCRIPTION_C");

                    b.Property<string>("PDescriptionL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("P_DESCRIPTION_L");

                    b.Property<string>("PMetaKeywords")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("P_META_KEYWORDS");

                    b.Property<string>("PMetaTitre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("P_META_TITRE");

                    b.Property<string>("PNom")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("P_NOM");

                    b.Property<string>("PSeo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("P_SEO");

                    b.Property<short?>("Preparation")
                        .HasColumnType("smallint")
                        .HasColumnName("PREPARATION");

                    b.Property<bool>("Publier")
                        .HasColumnType("bit")
                        .HasColumnName("PUBLIER");

                    b.Property<short?>("Rabais")
                        .HasColumnType("smallint")
                        .HasColumnName("RABAIS");

                    b.Property<short?>("Stock")
                        .HasColumnType("smallint")
                        .HasColumnName("STOCK");

                    b.HasKey("Prodid");

                    b.HasIndex(new[] { "Categorieid" }, "APPARTENIR_FK");

                    b.HasIndex(new[] { "Btqid" }, "VENDRE_FK");

                    b.ToTable("PRODUIT");
                });

            modelBuilder.Entity("E_Shop.Entities.RelaisLocB", b =>
                {
                    b.Property<int>("Btqid")
                        .HasColumnType("int")
                        .HasColumnName("BTQID");

                    b.Property<int>("Localisationid")
                        .HasColumnType("int")
                        .HasColumnName("LOCALISATIONID");

                    b.HasKey("Btqid", "Localisationid");

                    b.HasIndex(new[] { "Localisationid" }, "PROPOSER2_FK");

                    b.HasIndex(new[] { "Btqid" }, "PROPOSER_FK");

                    b.ToTable("RELAIS_LOC_B");
                });

            modelBuilder.Entity("E_Shop.Entities.RembTransact", b =>
                {
                    b.Property<int>("Remboursementid")
                        .HasColumnType("int")
                        .HasColumnName("REMBOURSEMENTID");

                    b.Property<int>("Transactionid")
                        .HasColumnType("int")
                        .HasColumnName("TRANSACTIONID");

                    b.HasKey("Remboursementid", "Transactionid");

                    b.HasIndex(new[] { "Transactionid" }, "TRAQUER2_FK");

                    b.HasIndex(new[] { "Remboursementid" }, "TRAQUER_FK");

                    b.ToTable("REMB_TRANSACT");
                });

            modelBuilder.Entity("E_Shop.Entities.Remboursement", b =>
                {
                    b.Property<int>("Remboursementid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REMBOURSEMENTID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Litigeid")
                        .HasColumnType("int")
                        .HasColumnName("LITIGEID");

                    b.Property<decimal?>("RMontant")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("R_MONTANT");

                    b.HasKey("Remboursementid");

                    b.HasIndex(new[] { "Litigeid" }, "DONNER_FK");

                    b.ToTable("REMBOURSEMENT");
                });

            modelBuilder.Entity("E_Shop.Entities.Remplacement", b =>
                {
                    b.Property<int>("Rempid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REMPID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Litigeid")
                        .HasColumnType("int")
                        .HasColumnName("LITIGEID");

                    b.Property<string>("RSuivilien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("R_SUIVILIEN");

                    b.Property<string>("RSuivinum")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("R_SUIVINUM");

                    b.HasKey("Rempid");

                    b.HasIndex(new[] { "Litigeid" }, "ENVOYER_FK");

                    b.ToTable("REMPLACEMENT");
                });

            modelBuilder.Entity("E_Shop.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("E_Shop.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("E_Shop.Entities.Transaction", b =>
                {
                    b.Property<int>("Transactionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRANSACTIONID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CODE");

                    b.Property<short?>("Mode")
                        .HasColumnType("smallint")
                        .HasColumnName("MODE");

                    b.Property<string>("Transactcontenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TRANSACTCONTENU");

                    b.Property<DateTime?>("Transactcrea")
                        .HasColumnType("datetime")
                        .HasColumnName("TRANSACTCREA");

                    b.Property<DateTime?>("Transactmodif")
                        .HasColumnType("datetime")
                        .HasColumnName("TRANSACTMODIF");

                    b.Property<short?>("Transactstatut")
                        .HasColumnType("smallint")
                        .HasColumnName("TRANSACTSTATUT");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("TYPE");

                    b.HasKey("Transactionid");

                    b.ToTable("TRANSACTION");
                });

            modelBuilder.Entity("E_Shop.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("E_Shop.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("E_Shop.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("E_Shop.Entities.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("E_Shop.Entities.Avi", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Avis")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_AVIS_AVIS3_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Avis")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_AVIS_AVIS2_PARTENAI")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("Avis")
                        .HasForeignKey("Prodid")
                        .HasConstraintName("FK_AVIS_AVIS_PRODUIT")
                        .IsRequired();

                    b.Navigation("Btq");

                    b.Navigation("IdNavigation");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.BcDetail", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutiquecommande", "Btqcmd")
                        .WithMany("BcDetails")
                        .HasForeignKey("Btqcmdid")
                        .HasConstraintName("FK_BC_DETAI_COMPORTER_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Livraison", "Livraison")
                        .WithMany("BcDetails")
                        .HasForeignKey("Livraisonid")
                        .HasConstraintName("FK_BC_DETAI_COMPORTER_LIVRAISO")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("BcDetails")
                        .HasForeignKey("Prodid")
                        .HasConstraintName("FK_BC_DETAI_COMPORTER_PRODUIT")
                        .IsRequired();

                    b.Navigation("Btqcmd");

                    b.Navigation("Livraison");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.Boutique", b =>
                {
                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Boutiques")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_BOUTIQUE_CREER_PARTENAI")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Politique", "Politique")
                        .WithMany("Boutiques")
                        .HasForeignKey("Politiqueid")
                        .HasConstraintName("FK_BOUTIQUE_APPLIQUER_POLITIQU")
                        .IsRequired();

                    b.Navigation("IdNavigation");

                    b.Navigation("Politique");
                });

            modelBuilder.Entity("E_Shop.Entities.Boutiquecommande", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Boutiquecommandes")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_BOUTIQUE_RECEVOIR_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Clientcommande", "Cltcmd")
                        .WithMany("Boutiquecommandes")
                        .HasForeignKey("Cltcmdid")
                        .HasConstraintName("FK_BOUTIQUE_ASSOCIER_CLIENTCO");

                    b.HasOne("E_Shop.Entities.Cmdetat", "Cmdetat")
                        .WithMany("Boutiquecommandes")
                        .HasForeignKey("Cmdetatid")
                        .HasConstraintName("FK_BOUTIQUE_COMPRENDR_CMDETAT")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Litige", "Litige")
                        .WithMany("Boutiquecommandes")
                        .HasForeignKey("Litigeid")
                        .HasConstraintName("FK_BOUTIQUE_ENGENDRER_LITIGE");

                    b.Navigation("Btq");

                    b.Navigation("Cltcmd");

                    b.Navigation("Cmdetat");

                    b.Navigation("Litige");
                });

            modelBuilder.Entity("E_Shop.Entities.Catnav", b =>
                {
                    b.HasOne("E_Shop.Entities.Categorie", "CatCategorie")
                        .WithMany("CatnavCatCategories")
                        .HasForeignKey("CatCategorieid")
                        .HasConstraintName("FK_CATNAV_REGROUPER_CATEGORI2")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Categorie", "Categorie")
                        .WithMany("CatnavCategories")
                        .HasForeignKey("Categorieid")
                        .HasConstraintName("FK_CATNAV_REGROUPER_CATEGORI1")
                        .IsRequired();

                    b.Navigation("CatCategorie");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("E_Shop.Entities.CcDetail", b =>
                {
                    b.HasOne("E_Shop.Entities.Clientcommande", "Cltcmd")
                        .WithMany("CcDetails")
                        .HasForeignKey("Cltcmdid")
                        .HasConstraintName("FK_CC_DETAI_LISTER_CLIENTCO")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Livraison", "Livraison")
                        .WithMany("CcDetails")
                        .HasForeignKey("Livraisonid")
                        .HasConstraintName("FK_CC_DETAI_LISTER3_LIVRAISO")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("CcDetails")
                        .HasForeignKey("Prodid")
                        .HasConstraintName("FK_CC_DETAI_LISTER2_PRODUIT")
                        .IsRequired();

                    b.Navigation("Cltcmd");

                    b.Navigation("Livraison");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.Clientcommande", b =>
                {
                    b.HasOne("E_Shop.Entities.Cmdetat", "Cmdetat")
                        .WithMany("Clientcommandes")
                        .HasForeignKey("Cmdetatid")
                        .HasConstraintName("FK_CLIENTCO_DETENIR_CMDETAT")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Facture", "Facture")
                        .WithMany("Clientcommandes")
                        .HasForeignKey("Factureid")
                        .HasConstraintName("FK_CLIENTCO_GENERER2_FACTURE");

                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Clientcommandes")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_CLIENTCO_PASSER_PARTENAI")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Paiement", "Paiement")
                        .WithMany("Clientcommandes")
                        .HasForeignKey("Paiementid")
                        .HasConstraintName("FK_CLIENTCO_PRENDRE2_PAIEMENT");

                    b.Navigation("Cmdetat");

                    b.Navigation("Facture");

                    b.Navigation("IdNavigation");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("E_Shop.Entities.Echange", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Echanges")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_ECHANGE_ECHANGE3_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Echanges")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_ECHANGE_ECHANGE_PARTENAI")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("Echanges")
                        .HasForeignKey("Prodid")
                        .HasConstraintName("FK_ECHANGE_ECHANGE2_PRODUIT")
                        .IsRequired();

                    b.Navigation("Btq");

                    b.Navigation("IdNavigation");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.Facture", b =>
                {
                    b.HasOne("E_Shop.Entities.Clientcommande", "Cltcmd")
                        .WithMany("Factures")
                        .HasForeignKey("Cltcmdid")
                        .HasConstraintName("FK_FACTURE_GENERER_CLIENTCO")
                        .IsRequired();

                    b.Navigation("Cltcmd");
                });

            modelBuilder.Entity("E_Shop.Entities.Format", b =>
                {
                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("Formats")
                        .HasForeignKey("Prodid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.Identification", b =>
                {
                    b.HasOne("E_Shop.Entities.Civilite", "Civ")
                        .WithMany("Identifications")
                        .HasForeignKey("Civid")
                        .HasConstraintName("FK_IDENTIFI_ETRE_CIVILITE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Identifications")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_IDENTIFI_IDENTIFIE_PARTENAI")
                        .IsRequired();

                    b.Navigation("Civ");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("E_Shop.Entities.Litige", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutiquecommande", "Btqcmd")
                        .WithMany("Litiges")
                        .HasForeignKey("Btqcmdid")
                        .HasConstraintName("FK_LITIGE_ENGENDRER_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Remboursement", "Remboursement")
                        .WithMany("Litiges")
                        .HasForeignKey("Remboursementid")
                        .HasConstraintName("FK_LITIGE_DONNER2_REMBOURS");

                    b.HasOne("E_Shop.Entities.Remplacement", "Remp")
                        .WithMany("Litiges")
                        .HasForeignKey("Rempid")
                        .HasConstraintName("FK_LITIGE_ENVOYER2_REMPLACE");

                    b.Navigation("Btqcmd");

                    b.Navigation("Remboursement");

                    b.Navigation("Remp");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraison", b =>
                {
                    b.HasOne("E_Shop.Entities.Localisation", "Localisation")
                        .WithMany("Livraisons")
                        .HasForeignKey("Localisationid")
                        .HasConstraintName("FK_LIVRAISO_DESTINER_LOCALISA")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Livraisonetat", "Lvretat")
                        .WithMany("Livraisons")
                        .HasForeignKey("Lvretatid")
                        .HasConstraintName("FK_LIVRAISO_CARACTERI_LIVRAISO")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Livraisontype", "Lvrtyp")
                        .WithMany("Livraisons")
                        .HasForeignKey("Lvrtypid")
                        .HasConstraintName("FK_LIVRAISO_DEFINIR_LIVRAISO")
                        .IsRequired();

                    b.Navigation("Localisation");

                    b.Navigation("Lvretat");

                    b.Navigation("Lvrtyp");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraisontype", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Livraisontypes")
                        .HasForeignKey("Btqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Btq");
                });

            modelBuilder.Entity("E_Shop.Entities.Localisation", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Localisations")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_LOCALISA_SITUER_BOUTIQUE");

                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Localisations")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_LOCALISA_POSSEDER_PARTENAI");

                    b.Navigation("Btq");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("E_Shop.Entities.Medium", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Media")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_MEDIA_BOUTMEDIA_BOUTIQUE");

                    b.HasOne("E_Shop.Entities.Categorie", "Categorie")
                        .WithMany("Media")
                        .HasForeignKey("Categorieid")
                        .HasConstraintName("FK_MEDIA_CATMEDIA_CATEGORI");

                    b.HasOne("E_Shop.Entities.Litige", "Litige")
                        .WithMany("Media")
                        .HasForeignKey("Litigeid")
                        .HasConstraintName("FK_MEDIA_LTGMEDIA_LITIGE");

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("Media")
                        .HasForeignKey("Prodid")
                        .HasConstraintName("FK_MEDIA_PRODMEDIA_PRODUIT");

                    b.Navigation("Btq");

                    b.Navigation("Categorie");

                    b.Navigation("Litige");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.Moyendepaiement", b =>
                {
                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Moyendepaiements")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_MOYENDEP_UTILISER_PARTENAI")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("E_Shop.Entities.PDetail", b =>
                {
                    b.HasOne("E_Shop.Entities.Format", "Format")
                        .WithMany("PDetails")
                        .HasForeignKey("Formatid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Panier", "Panier")
                        .WithMany("PDetails")
                        .HasForeignKey("Panierid")
                        .HasConstraintName("FK_P_DETAIL_CONTENIR_PANIER")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("PDetails")
                        .HasForeignKey("Prodid")
                        .HasConstraintName("FK_P_DETAIL_CONTENIR2_PRODUIT")
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Panier");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.PaieTransact", b =>
                {
                    b.HasOne("E_Shop.Entities.Paiement", "Paiement")
                        .WithMany("PaieTransacts")
                        .HasForeignKey("Paiementid")
                        .HasConstraintName("FK_PAIE_TRA_TRACER_PAIEMENT")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Transaction", "Transaction")
                        .WithMany("PaieTransacts")
                        .HasForeignKey("Transactionid")
                        .HasConstraintName("FK_PAIE_TRA_TRACER2_TRANSACT")
                        .IsRequired();

                    b.Navigation("Paiement");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("E_Shop.Entities.Paiement", b =>
                {
                    b.HasOne("E_Shop.Entities.Clientcommande", "Cltcmd")
                        .WithMany("Paiements")
                        .HasForeignKey("Cltcmdid")
                        .HasConstraintName("FK_PAIEMENT_PRENDRE_CLIENTCO")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Moyendepaiement", "Mdp")
                        .WithMany("Paiements")
                        .HasForeignKey("Mdpid")
                        .HasConstraintName("FK_PAIEMENT_REGLER_MOYENDEP")
                        .IsRequired();

                    b.Navigation("Cltcmd");

                    b.Navigation("Mdp");
                });

            modelBuilder.Entity("E_Shop.Entities.Panier", b =>
                {
                    b.HasOne("E_Shop.Entities.Partenaire", "IdNavigation")
                        .WithMany("Paniers")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_PANIER_DISPOSER_PARTENAI");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("E_Shop.Entities.Partenaire", b =>
                {
                    b.HasOne("E_Shop.Entities.Panier", "Panier")
                        .WithMany("Partenaires")
                        .HasForeignKey("Panierid")
                        .HasConstraintName("FK_PARTENAI_DISPOSER2_PANIER");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("E_Shop.Entities.ProdLvrType", b =>
                {
                    b.HasOne("E_Shop.Entities.Livraisontype", "Livraisontype")
                        .WithMany("ProdLivraisonTypes")
                        .HasForeignKey("LvrTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Produit", "Prod")
                        .WithMany("ProdLivraisonTypes")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livraisontype");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("E_Shop.Entities.Produit", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("Produits")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_PRODUIT_VENDRE_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("Categorieid")
                        .HasConstraintName("FK_PRODUIT_APPARTENI_CATEGORI")
                        .IsRequired();

                    b.Navigation("Btq");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("E_Shop.Entities.RelaisLocB", b =>
                {
                    b.HasOne("E_Shop.Entities.Boutique", "Btq")
                        .WithMany("RelaisLocBs")
                        .HasForeignKey("Btqid")
                        .HasConstraintName("FK_RELAIS_L_PROPOSER_BOUTIQUE")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Localisation", "Localisation")
                        .WithMany("RelaisLocBs")
                        .HasForeignKey("Localisationid")
                        .HasConstraintName("FK_RELAIS_L_PROPOSER2_LOCALISA")
                        .IsRequired();

                    b.Navigation("Btq");

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("E_Shop.Entities.RembTransact", b =>
                {
                    b.HasOne("E_Shop.Entities.Remboursement", "Remboursement")
                        .WithMany("RembTransacts")
                        .HasForeignKey("Remboursementid")
                        .HasConstraintName("FK_REMB_TRA_TRAQUER_REMBOURS")
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Transaction", "Transaction")
                        .WithMany("RembTransacts")
                        .HasForeignKey("Transactionid")
                        .HasConstraintName("FK_REMB_TRA_TRAQUER2_TRANSACT")
                        .IsRequired();

                    b.Navigation("Remboursement");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("E_Shop.Entities.Remboursement", b =>
                {
                    b.HasOne("E_Shop.Entities.Litige", "Litige")
                        .WithMany("Remboursements")
                        .HasForeignKey("Litigeid")
                        .HasConstraintName("FK_REMBOURS_DONNER_LITIGE")
                        .IsRequired();

                    b.Navigation("Litige");
                });

            modelBuilder.Entity("E_Shop.Entities.Remplacement", b =>
                {
                    b.HasOne("E_Shop.Entities.Litige", "Litige")
                        .WithMany("Remplacements")
                        .HasForeignKey("Litigeid")
                        .HasConstraintName("FK_REMPLACE_ENVOYER_LITIGE")
                        .IsRequired();

                    b.Navigation("Litige");
                });

            modelBuilder.Entity("E_Shop.Entities.RoleClaim", b =>
                {
                    b.HasOne("E_Shop.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("E_Shop.Entities.UserClaim", b =>
                {
                    b.HasOne("E_Shop.Entities.Partenaire", "Partenaire")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("E_Shop.Entities.UserLogin", b =>
                {
                    b.HasOne("E_Shop.Entities.Partenaire", "Partenaire")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("E_Shop.Entities.UserRole", b =>
                {
                    b.HasOne("E_Shop.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Shop.Entities.Partenaire", "Partenaire")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partenaire");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("E_Shop.Entities.Boutique", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Boutiquecommandes");

                    b.Navigation("Echanges");

                    b.Navigation("Livraisontypes");

                    b.Navigation("Localisations");

                    b.Navigation("Media");

                    b.Navigation("Produits");

                    b.Navigation("RelaisLocBs");
                });

            modelBuilder.Entity("E_Shop.Entities.Boutiquecommande", b =>
                {
                    b.Navigation("BcDetails");

                    b.Navigation("Litiges");
                });

            modelBuilder.Entity("E_Shop.Entities.Categorie", b =>
                {
                    b.Navigation("CatnavCatCategories");

                    b.Navigation("CatnavCategories");

                    b.Navigation("Media");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("E_Shop.Entities.Civilite", b =>
                {
                    b.Navigation("Identifications");
                });

            modelBuilder.Entity("E_Shop.Entities.Clientcommande", b =>
                {
                    b.Navigation("Boutiquecommandes");

                    b.Navigation("CcDetails");

                    b.Navigation("Factures");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("E_Shop.Entities.Cmdetat", b =>
                {
                    b.Navigation("Boutiquecommandes");

                    b.Navigation("Clientcommandes");
                });

            modelBuilder.Entity("E_Shop.Entities.Facture", b =>
                {
                    b.Navigation("Clientcommandes");
                });

            modelBuilder.Entity("E_Shop.Entities.Format", b =>
                {
                    b.Navigation("PDetails");
                });

            modelBuilder.Entity("E_Shop.Entities.Litige", b =>
                {
                    b.Navigation("Boutiquecommandes");

                    b.Navigation("Media");

                    b.Navigation("Remboursements");

                    b.Navigation("Remplacements");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraison", b =>
                {
                    b.Navigation("BcDetails");

                    b.Navigation("CcDetails");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraisonetat", b =>
                {
                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("E_Shop.Entities.Livraisontype", b =>
                {
                    b.Navigation("Livraisons");

                    b.Navigation("ProdLivraisonTypes");
                });

            modelBuilder.Entity("E_Shop.Entities.Localisation", b =>
                {
                    b.Navigation("Livraisons");

                    b.Navigation("RelaisLocBs");
                });

            modelBuilder.Entity("E_Shop.Entities.Moyendepaiement", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("E_Shop.Entities.Paiement", b =>
                {
                    b.Navigation("Clientcommandes");

                    b.Navigation("PaieTransacts");
                });

            modelBuilder.Entity("E_Shop.Entities.Panier", b =>
                {
                    b.Navigation("Partenaires");

                    b.Navigation("PDetails");
                });

            modelBuilder.Entity("E_Shop.Entities.Partenaire", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Boutiques");

                    b.Navigation("Claims");

                    b.Navigation("Clientcommandes");

                    b.Navigation("Echanges");

                    b.Navigation("Identifications");

                    b.Navigation("Localisations");

                    b.Navigation("Logins");

                    b.Navigation("Moyendepaiements");

                    b.Navigation("Paniers");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("E_Shop.Entities.Politique", b =>
                {
                    b.Navigation("Boutiques");
                });

            modelBuilder.Entity("E_Shop.Entities.Produit", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("BcDetails");

                    b.Navigation("CcDetails");

                    b.Navigation("Echanges");

                    b.Navigation("Formats");

                    b.Navigation("Media");

                    b.Navigation("PDetails");

                    b.Navigation("ProdLivraisonTypes");
                });

            modelBuilder.Entity("E_Shop.Entities.Remboursement", b =>
                {
                    b.Navigation("Litiges");

                    b.Navigation("RembTransacts");
                });

            modelBuilder.Entity("E_Shop.Entities.Remplacement", b =>
                {
                    b.Navigation("Litiges");
                });

            modelBuilder.Entity("E_Shop.Entities.Transaction", b =>
                {
                    b.Navigation("PaieTransacts");

                    b.Navigation("RembTransacts");
                });
#pragma warning restore 612, 618
        }
    }
}
